# data
dataset: cifar10

# model
model_name: rn18
baseline_path: /home/dbreen/Documents/tddl/pretrained/cifar10/logs/rn18/baselines/1646417743/rn18_18_dNone_128_sgd_l0.1_g0.1_sTrue/cnn_best.pth

# training
batch: 128
epochs: 25
optimizer: 'adam'
lr: 1.0e-5
gamma: 0

# factorization
factorization: 'cp'
decompose_weights: true
rank: 0.1
layers:
- [63,60]

# datalogging
data_dir: "/home/dbreen/Documents/tddl/bigdata/cifar10" 
logdir: "/home/dbreen/Documents/tddl/bigdata/cifar10/logs/rn18/decomposed" 

# hardware
data_workers: /home/dbreen/Documents/tddl/pretrained/cifar10/logs/rn18/baselines/1646417743/rn18_18_dNone_128_sgd_l0.1_g0.1_sTrue
